// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQqrye3mW1Ol6KsSb2XXeZPm5IlGou0F8',
    appId: '1:1024512016620:web:0ddc3d73510d495f05a5c9',
    messagingSenderId: '1024512016620',
    projectId: 'housecraft-bd864',
    authDomain: 'housecraft-bd864.firebaseapp.com',
    storageBucket: 'housecraft-bd864.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO413sTw8QxVBOglAVNXyyDHm_BBvwRwM',
    appId: '1:1024512016620:android:de220d620bfbd49105a5c9',
    messagingSenderId: '1024512016620',
    projectId: 'housecraft-bd864',
    storageBucket: 'housecraft-bd864.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXAaMcwhQ-5PkIB7ISdFwLXjulJcN5fME',
    appId: '1:1024512016620:ios:9b126fe7575b97e705a5c9',
    messagingSenderId: '1024512016620',
    projectId: 'housecraft-bd864',
    storageBucket: 'housecraft-bd864.firebasestorage.app',
    iosBundleId: 'com.sixamtech.demandium.user',
  );
}
