// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDQqrye3mW1Ol6KsSb2XXeZPm5IlGou0F8",
      authDomain: "housecraft-bd864.firebaseapp.com",
      projectId: "housecraft-bd864",
      storageBucket: "housecraft-bd864.firebasestorage.app",
      messagingSenderId: "1024512016620",
      appId: "1:1024512016620:web:5ead8ae8621c656105a5c9");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyBRm0BwPdCN5fysWybkrlQkf5nYYX2_asw",
      authDomain: "makesmyhomeuser.firebaseapp.com",
      projectId: "makesmyhomeuser",
      storageBucket: "makesmyhomeuser.firebasestorage.app",
      messagingSenderId: "540954631359",
      appId: "1:540954631359:android:3f0f563574b9cc6a907a0a");

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyBO413sTw8QxVBOglAVNXyyDHm_BBvwRwM",
      authDomain: "housecraft-bd864.firebaseapp.com",
      projectId: "housecraft-bd864",
      storageBucket: "housecraft-bd864.firebasestorage.app",
      messagingSenderId: "1024512016620",
      appId: "1:1024512016620:ios:bqeh1182qf5l4ehuhdu5025ls55dc08d");
}
